from pogema import pogema_v0, GridConfig

grid = """
.....#.....
.....#.....
...........
.....#.....
.....#.....
#.####.....
.....###.##
.....#.....
.....#.....
...........
.....#.....
"""

# Define new configuration with 8 randomly placed agents
grid_config = GridConfig(map=grid, num_agents=1,integration="PettingZoo",obs_radius=1)

# Create custom Pogema environment
env = pogema_v0(grid_config=grid_config)
print(env.reset())
env.render()
